language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t iamuv2000/docker-for-dummies -f Dockerfile.dev . 

script:
  - docker run -e CI=true iamuv2000/docker-for-dummies npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: 'react-docker'
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-502279622047"
  bucket_path: 'react-docker'
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

